# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CW4uyb17P-ykbo1E3Fg7N_7pVCtwcI0S
"""



import numpy as np
from scipy import integrate
from scipy.interpolate import interp1d
import matplotlib.pyplot as plt

# Physical constants
h = 6.62607015e-34      # Planck's constant (J·s)
c = 2.99792458e8        # Speed of light (m/s)
k = 1.380649e-23        # Boltzmann constant (J/K)
q = 1.602176634e-19     # Elementary charge (C)

# USER INPUTS
# =============================================================================
EQE_FILE = "/content/test eqe.csv"

DEVICE_TEMP = float(input("Enter Device Temperature (K): "))
LAMBDA_MIN = float(input("Enter Minimum Wavelength (nm): "))
LAMBDA_MAX = float(input("Enter Maximum Wavelength (nm): "))
JSC_INPUT = float(input("Enter Jsc (mA/cm²): "))
PLQY = float(input("Enter PLQY (0-1 or %): "))

# Convert PLQY if entered as percentage
if PLQY > 1:
    PLQY = PLQY / 100.0

# FUNCTIONS
# =============================================================================
def load_eqe(filename):
    data = np.genfromtxt(filename, delimiter=',', skip_header=1)
    return data[:, 0], data[:, 1] / 100.0

def blackbody_flux(wavelength_nm, temperature):
    """Black body photon flux Φ_BB(λ,T) in photons/(m²·s·nm)"""

    lam = wavelength_nm * 1e-9
    exp_term = np.clip((h * c) / (lam * k * temperature), None, 700)
    return np.pi * (2.0 * np.pi * c / lam**4) / (np.exp(exp_term) - 1.0) * 1e-9

def calculate_qfls(wavelengths, eqe_values, lam_min, lam_max, temp, jsc_mA_cm2, plqy):
    """Calculate J0,rad and QFLS with PLQY"""

    eqe_func = interp1d(wavelengths, eqe_values, kind='linear', bounds_error=False, fill_value=0.0)
    wl = np.linspace(lam_min, lam_max, 100000)
    eqe = eqe_func(wl)

    # J0,rad = q × ∫ EQE(λ) × Φ_BB(λ, T_device) dλ
    phi_bb = blackbody_flux(wl, temp)
    phi_bb_eqe = phi_bb * eqe
    area_eqe = integrate.simpson(eqe, x=wl)

    J0rad_A_m2 = q * integrate.simpson(phi_bb_eqe, x=wl)
    J0rad_mA_cm2 = J0rad_A_m2 * 0.1

    # QFLS = kT × ln(PLQY × Jsc / J0,rad)
    Jsc_A_m2 = jsc_mA_cm2 / 0.1
    Vt = (k * temp) / q
    QFLS = Vt * np.log(plqy * Jsc_A_m2 / J0rad_A_m2)
    QFLS_rad = Vt * np.log(Jsc_A_m2 / J0rad_A_m2)  # Radiative limit (PLQY=1)
    delta_V = QFLS_rad - QFLS  # Non-radiative loss

    return {'wl': wl, 'eqe': eqe, 'phi_bb_eqe': phi_bb_eqe, 'area_eqe': area_eqe,
            'J0rad': J0rad_mA_cm2, 'QFLS': QFLS, 'QFLS_rad': QFLS_rad,
            'delta_V': delta_V, 'Vt': Vt}

def plot_results(results, wavelengths, eqe_values):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

    # Plot 1: EQE with area
    ax1.plot(results['wl'], results['eqe']*100, 'g-', lw=2)
    ax1.scatter(wavelengths, eqe_values*100, c='darkgreen', s=10, alpha=0.5)
    ax1.fill_between(results['wl'], results['eqe']*100, alpha=0.3, color='green')
    ax1.set_xlabel('Wavelength (nm)')
    ax1.set_ylabel('EQE (%)')
    ax1.set_title(f'EQE Curve\nArea = {results["area_eqe"]:.2f} nm')
    ax1.grid(True, alpha=0.3)
    ax1.set_ylim(0, 100)

    # Plot 2: Φ_BB × EQE (J0,rad integrand)
    ax2.plot(results['wl'], results['phi_bb_eqe'], 'r-', lw=2)
    ax2.fill_between(results['wl'], results['phi_bb_eqe'], alpha=0.3, color='red')
    ax2.set_xlabel('Wavelength (nm)')
    ax2.set_ylabel('Φ_BB × EQE [photons/(m²·s·nm)]')
    ax2.set_title(f'J₀,rad Integrand (T = {DEVICE_TEMP:.0f}K)\nJ₀,rad = {results["J0rad"]:.4e} mA/cm²')
    ax2.grid(True, alpha=0.3)
    ax2.ticklabel_format(style='scientific', axis='y', scilimits=(0,0))

    plt.tight_layout()
    plt.savefig('qfls_plot.png', dpi=150)
    plt.show()

# MAIN
# =============================================================================

wavelengths, eqe_values = load_eqe(EQE_FILE)
results = calculate_qfls(wavelengths, eqe_values, LAMBDA_MIN, LAMBDA_MAX, DEVICE_TEMP, JSC_INPUT, PLQY)

print("\n" + "="*55)
print("                    RESULTS")
print("="*55)
print(f"\n  Device Temperature     = {DEVICE_TEMP} K")
print(f"  Thermal Voltage (kT/q) = {results['Vt']*1000:.4f} mV")
print(f"  Area under EQE         = {results['area_eqe']:.2f} nm")
print(f"\n  Jsc (input)            = {JSC_INPUT:.4f} mA/cm²")
print(f"  PLQY                   = {PLQY*100:.2f} %")
print(f"  J₀,rad                 = {results['J0rad']:.4e} mA/cm²")

print(f"  QFLS_rad (PLQY=100%) = {results['QFLS_rad']:.4f} V ({results['QFLS_rad']*1000:.2f} meV)")
print(f"  ΔV_non-rad           = {results['delta_V']:.4f} V ({results['delta_V']*1000:.2f} meV)  ")


print(f"  QFLS = {results['QFLS']:.4f} V  ({results['QFLS']*1000:.2f} meV)  ")
print(f"  (with PLQY = {PLQY*100:.2f}%)                 ")


plot_results(results, wavelengths, eqe_values)
print("\n  ✓ Plot saved as 'qfls_plot.png'")